- lib/friendly_id/initializer.rb
The method name is `should_generate_new_friendly_id?` not `should_generate_new_friendly_id`.
That seems rather important. :-)
> Fix minor typo in documentation

- lib/friendly_id.rb
- lib/friendly_id/sequentially_slugged.rb
- test/sequentially_slugged_test.rb
This provides an addon that enables sequential slugs for conflict resolution, mimicking the behaviour of friendly_id v4.
Well formed candidates combined with UUIDs as a fallback will almost always be the better solution for resolving slug conflicts. That said, there are circumstances when this is either not possible or undesirable. For example, either good candidates cannot be formed, or the existing behaviour needs to be maintained for consistency.
I have recently had to deal with this situation whilst upgrading a [large Rails 3 application to Rails 4](https://github.com/alphagov/whitehall/pull/1958). In this case it's not possible to form appropriate candidates for many of the sluggable models, and UUIDs would make new URLs inconsistent and "ugly". Ultimately it's both cheaper and far …
> Addon for numerically sequential slugs

- .travis.yml
@norman I can't figure out the failure, and the driver itself says it's not quite ready for ActiveRecord 4.2 so this seems acceptable for now.
I've also removed a now useless rbx + Travis CI workaround where we had to override the bundle install command.  This should play much more nicely with bundle caching now.
> CI: allow postgres + jruby + activerecord 4.2 failures

- lib/friendly_id/candidates.rb
- test/candidates_test.rb
Hi
The mean aim of this commit is to provide access to generated slug candidates without direct AR manipulations
```ruby 
FriendlyId::Candidates.new(model, model.slug_candidates).each 
``` 
So, it seems reasonable for me to use this syntax instead of calling #save. It can be written to return Enumerator instead of array, but it will be not so readable and will complicate method.
> Make Candidates#each iterable without block.

- lib/friendly_id/history.rb
- test/history_test.rb
Slugs can be reused by different model instances when the slug is reassigned directly, as in `model_instance.slug = "value_already_in_history"`. This means you can have more than one instance of the slug value for the same type in the history. 
Currently, in this scenario, the first model instance to use the slug value will win out in a history search, because the `slug_table_record` method relies on natural sorting (by id) and selects the first record.
It seems more logical to retrieve the model instance that most recently used the slug value, which would actually be the last record with the slug value in the slug history table. 
This PR sets an explicit descending order by created_at on the history table search, so that the selected model is the last one to use the target slug value.
> ensure slug history prefers the record that most recently used the slug

- lib/friendly_id/base.rb
Starting with Rails 4.2, calculating the `changes` hash in activerecord is much more expensive since it now tracks in-place changes in json/jsonb/hstore fields. We noticed a ~10x hit to performance due to these changes being calculated on every `to_param` call on some of our models with large json fields. 
This change simply checks for changes in a less expensive way before calculating the `changes` hash if the param field has indeed changed. 
All tests still pass and I didn't see a need to add additional testing.
> Don't calculate all changes just to check if the param field has changed

- README.md
Add go rails video to documentation and fix styling issue with the two links in articles being on the same line.
> add GoRails video to readme documentation

- gemfiles/Gemfile.rails-4.0.rb
- gemfiles/Gemfile.rails-4.1.rb
- lib/friendly_id/finders.rb
- lib/friendly_id/history.rb
- test/history_test.rb
Fixed #717.
Module `:finders` includes methods from `friendly_id_config.finder_methods` into base class. But module `:history` replaces this methods. So, to make `:finders` and `:history` works together those methods must be reincluded into base class during initialization of `:history`.
> Fixed problem that occurred when module :history was used after :finders

- lib/friendly_id/history.rb
- lib/friendly_id/simple_i18n.rb
Since including `finders` isn't mentioned (and it's out of scope), we should include the 5.0+ syntax instead of the old one.
> Update docs to use v5.0+ syntax for finding

- lib/friendly_id/sequentially_slugged.rb
- test/sequentially_slugged_test.rb
Previously `friendly_id_config.base` was checked on presence in `should_generate_new_friendly_id?`. And let's imagine that we have multiple slug candidates, but all of them is nil. In this case we will have something like `[nil, nil]` as base for slug and `presence?` for this array will be evalutated to true. But all of slug canidates is nil, right? Booom! Exception during execution of `resolve_friendly_id_conflict`.
> Frienldy_id should not generate a slug when all of canidates is nil.

- README.md
Right now it's italicized, which is very easy to skip over. Additionally, this switches that line HTML `<em>`'s to markdown `**`'s.
> Embolden the link to the more comprehensive docs

- lib/friendly_id/history.rb
Call of `joins(:slugs)` in `FriendlyId::History#exists_by_friendly_id?` was expected by `FriendlyId::History#scope_for_slug_generator`, but it was useless for `exists_by_friendly_id?` itself and led to additional INNER JOIN in query without any reason. So, it was moved.
> Moved joins on slugs table from exists_by_friendly_id to scope_for_slug_generator

- lib/friendly_id/base.rb
- lib/friendly_id/configuration.rb
- lib/friendly_id/history.rb
- test/history_test.rb
Hey guys!
This adds the ability not to delete historic slugs when the sluggable class is destroyed.
When using acts_as_paranoid on a sluggable models, we aren't actually deleting the models when calling destroy. If we delete the slugs, we’re losing the history. We're also setting up a condition where a unique constraint ends up getting violated.
This is a revival of https://github.com/norman/friendly_id/pull/268
> Conditionally turn off :dependent => :destory on FriendlyId::Slugs 

- lib/friendly_id.rb
- lib/friendly_id/object_utils.rb
Simplified PR #674 as was discussed in it's conversation.
If we know that class is "unfriendly" because it's included in our list of such classes we can just return appropriate true / false from re-implemented friendly_id? / unfriendly_id? instead of searching through FriendlyId::UNFRIENDLY_CLASSES each time when those methods are called.
> Mixed FriendlyId::UnfriendlyUtils to all classes that are listed in FriendlyId::UNFRIENDLY_CLASSES.

- gemfiles/Gemfile.rails-5.0.rb
I've been using friendly_id along with rails5-rc since it was released with no issues. 
Updating the rails-5 gem to use rc1. 
@djsegal was enquiring about the stability of rc1 here: https://github.com/norman/friendly_id/pull/753  - figured it would make sense to update the specs to use the latest version.
> Update rails-5 gem with activerecord/railties 5.0.0

- lib/friendly_id.rb
Trying to require friendly_id outside of rails results in `uninitialized constant FriendlyId::ActiveRecord`.  My use case is preloading gems with sidekiq swarm.
Adding a require fixes this use case.
> Require active record before using it

- lib/friendly_id/slugged.rb
- test/schema.rb
- test/slugged_test.rb
1f8af74b mistakenly assigns to the literal `slug` method, rather than the configured `slug_column`. As a result, models using a custom `slug_column` get an error raised when validations fail that `slug=` is an undefined method.
Fixes #765.
> Assign to configured slug column, not "slug", when validation fails

- README.md
Rails 5 Active Record models now inherit from `ApplicationRecord` by default. I thought it appropriate to reflect this in the readme.
> Change ActiveRecord::Base to ApplicationRecord

- lib/friendly_id/candidates.rb
Hey,
This PR splits `Candidates#each` method, thus separating actual yielding from constructing/filtering elements. 
A minor change, but we can further improve from here: one idea is to create a `Candidate` class, and move slug construction/validation there. 
Should also solve CodeClimate Issue (https://codeclimate.com/github/norman/friendly_id/FriendlyId::Candidates#complexity)
Main idea is to make this part of code more readable (while keeping simplicity/flexibility)
> Split Candidates#each in few methods

- .travis.yml
- gemfiles/Gemfile.rails-5.0.rb
- lib/friendly_id/finder_methods.rb
- test/schema.rb
According to @parndt [comment](https://github.com/norman/friendly_id/pull/809#issuecomment-315561165)
> Update specs and drop support for ruby 2.0.0

- lib/friendly_id/base.rb
- lib/friendly_id/initializer.rb
- lib/friendly_id/slugged.rb
- test/slugged_test.rb
By: 
- https://github.com/norman/friendly_id/issues/190
- https://github.com/norman/friendly_id/pull/802
> Allow to set size limit for slug

- README.md
Related issue #817 
To be solved with #816 (Update for Rails 5.1)
Added a few lines to the Readme how to prevent the warning that appears when running db:migrate on the  generated migration.
No big deal, but it speeds things up a bit for dev happiness 🎁
> How to: Prevent warning on db:migrate in Rails 5.1

- README.md
There was an extra set of backticks in the README, so **```shell** was showing up in the code block.
> Remove extra ``` in README

- lib/friendly_id/reserved.rb
- lib/friendly_id/scoped.rb
- lib/friendly_id/slug_generator.rb
- lib/friendly_id/slugged.rb
- test/reserved_test.rb
Closes #830 
This adds an option to FriendlyId::Reserved::Configuration to treat reserved words as conflicts rather than exceptions. When there is no good candidate, a UUID will be appended, matching the existing conflict behavior.
This could be implemented differently, but I tried to keep with the same patterns used in the gem.
Testing: 
-  Changes are opt-in, so behavior is non-breaking.
- New and old specs pass.
> option to treat reserved words as conflicts, fix #830

- lib/friendly_id/finder_methods.rb
- test/helper.rb
- test/history_test.rb
1. ActiveSupport deprecation warning for ActiveSupport 4.2:
DEPRECATION WARNING: You did not specify a value for the configuration option `active_support.test_order`. In Rails 5, the default value of this option will change from `:sorted` to `:random`.
To disable this warning and keep the current behavior, you can add the following line to your `config/environments/test.rb`:
Rails.application.configure do
config.active_support.test_order = :sorted
end
Alternatively, you can opt into the future behavior by setting this option to `:random`. (called from test_order at …/gems/activesupport-4.2.10/lib/active_support/test_case.rb:42)
2. Ruby warning:
friendly_id/test/history_test.rb:251: warning: assigned but unused variable - e
3. Ruby warning:
friendly_id/lib/friendly_id/finder_methods.rb:53: …
> Removes multiple warnings when running 'bundle exec rake test'

- test/history_test.rb
DependentDestroyTest used to inherit from HistoryTest,
which run tests for a DependentDestroyTest#model_class
that was not overriden anyway.
Previously had 431 tests. Now we have 403 total tests
> Removes redundant HistoryTest

- friendly_id.gemspec
- lib/friendly_id/slug.rb
- test/history_test.rb
- test/schema.rb
Probably fixes #822, as the test case is likely what he has encountered. His report most probably required 2 things to be true:
1. He used `friendly_id ... :dependent => false`
2. friendly_id is used in a Rails 5.0 app
Previously, when a sluggable is soft deleted and a slug persists
(i.e. :dependent => false), slug can't find its corresponding
sluggable.
Additionally, in Rails 5.0, belongs_to_required_by_default has been
introduced to be true by default (unless changed back to false), therefore making Friendly::Slug
invalid with the error message 'Sluggable must exist'.
> Slugs should always find their sluggable, even when they are soft deleted by acts_as_paranoid

- friendly_id.gemspec
- lib/friendly_id/history.rb
- lib/friendly_id/migration.rb
- lib/friendly_id/sequentially_slugged.rb
- test/schema.rb
This fixes migration warnings which were introduced in Rails 5.0 and became errors in Rails 5.1.
This also fixes deprecation warnings introduced in Rails 5.2
> DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "...". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().
I believe the build error here is the same that is on master
> Fix deprecation warnings on Rails 5.2 (and some 5.1 fixes)

- lib/friendly_id.rb
- lib/friendly_id/object_utils.rb
- lib/friendly_id/railtie.rb
- test/object_utils_test.rb
If FriendlyId references `ActiveRecord::Base` while it is loading as part of a Rails application, it triggers the `on_load` event for ActiveRecord, which as part of the loading process sets the current configuration values of ActiveRecord. If any initializers try to influence that configuration (e.g. changing defaults in `new_framework_defaults.rb` for an app that's been upgraded), these changes will have no effect because the configuration has already been set in place.
To avoid this, we need to avoid triggering the `on_load` event by wrapping the reference to `ActiveRecord::Base` in an initializer block. The simplest way of doing this is with a `Railtie`, which will be automatically loaded if FriendlyId is required as part of Rails.
Testing this change is unfortunately quite hard; it …
> Defer loading of ActiveRecord to avoid config issues

- lib/friendly_id/history.rb
It also makes `first_by_friendly_id` better because base implementation
in `FriendlyId::FinderMethods` uses `find_by` which is optimized in
Rails 4.2 (so called "Adequate Record").
> Refactor History::FinderMethods: use base implementations.

- lib/friendly_id/candidates.rb
Hello,
it's nothing critical, just a minor style PR: `lib/friendly_id/candidates.rb` had 2 **private** statements 😊
> Remove second 'private' statement from  `lib/friendly_id/candidates.rb`

- lib/friendly_id/base.rb
- test/slugged_test.rb
(... and also remove deprecation warnings under Rails 5.1)
I originally started investigating this as part of #816 (see some discussion there about `to_param` from the perspective of the deprecation warnings), and also #862 (which features the first version of the callback test I've used here).
On the latter, it became clear that there were actually two issues: the deprecation warnings, and the behaviour of `to_param` in callbacks. I decided to write an explicit test for the callback behaviour here, and included a bunch of other tests about `to_param` in various scenarios.
The "fix" basically involves deleting all the dirty tracking code within `to_param`, which seems superficially crazy to me, but all the tests pass, so either we don't need that code, or we are missing some key tests …
> Fix to_param in ActiveRecord callbacks

- README.md
Migration warnings on Rails 5 were fixed in https://github.com/norman/friendly_id/commit/2a7121df300e0acc2e18c75f83ad9e17152f5a9f
> Remove temp solution for Rails 5 from README.md

- lib/friendly_id/finder_methods.rb
- test/numeric_slug_test.rb
If a record is created with a slug that is an integer (123, for example), `Model.friendly.find("123")` finds the correct record with slug of "123", but `Model.friendly.exists?("123")` returns false.
Referencing the comment [here](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/finder_methods.rb#L8):
```ruby
```
`.find()` is correctly finding the record by its slug "123".  [Code reference](https://github.com/norman/friendly_id/blob/master/lib/friendly_id/finder_methods.rb#L18)
```ruby
def find(*args)
id = args.first
return super if args.count != 1 || id.unfriendly_id?
first_by_friendly_id(id).tap {|result| return result unless result.nil?}
return super if potential_primary_key?(id)
raise ActiveRecord::RecordNotFound, "can't find record with friendly id: #{id.inspect}"
end …
```
> Fix exists? to behave the same as find for numeric slugs

- lib/friendly_id/history.rb
- lib/friendly_id/scoped.rb
- lib/friendly_id/sequentially_slugged.rb
- test/sequentially_slugged_test.rb
`SequentiallySlugged` with `History` doesn't look into previously used slugs, which can result in a wrong `last_sequence_number` and failure.
> fix History + SequentiallySlugged + Scope issues

- lib/friendly_id/migration.rb
A `sluggable_id` index alone isn't much use since the `sluggable_id` only makes sense in the context of a `sluggable_type`. This allows for much faster look ups (and better query planning) when searching by a sluggable.
> Use composite index for queries by sluggable

- README.md
Re: #886 
If you follow the steps on the README you'll see a `Undefined method 'slug'` error. Looks like it's because there's a missing step in the documentation. 
Let me know what you think. Thanks!
> Add missing step to the README file

- README.md
Seems like the original site has been hacked or something.
I suggest we change the link until it's back.
> Temporarily direct bugreporting info link to something more appropriate

- .travis.yml
This PR **updates the CI matrix** to the latest generally available Ruby versions.
Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known
- move env variables into the env.global section
- drop unused `sudo: false` settings - see https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> CI: Use 2.6.3, 2.5.5, 2.4.6, 2.3.8

- friendly_id.gemspec
The RubyGems property rubyforge_project is removed without a replacement.
> gemspec: Remove rubyforge_project, it is EOL

- Changelog.md
I noticed the changelog is missing when I wanted to update friendly_id, so I compiled the relevant bits.
> Add missing changelog for 5.2.5

- lib/friendly_id/history.rb
- test/history_test.rb
In order to record history, we should check if there is a new slug.
If the record uses the scoped module we should also check if there is **a change in the scope**.
> Record history when scope changes but slug does not

- lib/friendly_id/history.rb
The current example code only works correctly for the `#show` action. If the user is using `find_post` for anything other than `#show`, it will re-direct a URL for `#edit` using the new slug to the `#show` for the new slug, making it impossible to edit (or update or destroy)
Note that this will redirect from `/posts/old_slug/edit` to `posts/new_slug`, so from `#edit` to `#show`. The code I implemented actually checks to see if the action_name is 'edit', and if it is, re-direct to the correct edit path. For sake of simplicity, I think it's fine to have the docs re-direct to the `#show`.
> Use the request slug instead of the whole path

- friendly_id.gemspec
According to https://github.com/norman/friendly_id/pull/824
> Set required_ruby_version to >= 2.1.0

- Changelog.md
- lib/friendly_id/finder_methods.rb
- test/finders_test.rb
Hello. This PR is about fixing the first issue of #785 by using `id.downcase` instead of `id` in `first_by_friendly_id` method. In this way if the url is like `users/John-Doe` or `users/JOHN-DOE`, it will search by `john-doe` in database.
Currently, it `find_by` with `id`.(case-sensitive)
```ruby
def first_by_friendly_id(id)
find_by(friendly_id_config.query_field => id)
end
```
It `find_by` with id.downcase.(case-insensitive)
```ruby
def first_by_friendly_id(id)
find_by(friendly_id_config.query_field => id.downcase)
end
```
The tests for the change have been added and all have passed.
> Case Insensitivity for `id`, fixes #785

- lib/friendly_id/history.rb
Before this change, when saving a new model with history, the following SQL
is generated to populate the `friendly_id_slugs` table (example uses `scoped` as well):
```sql
-- FriendlyId::Slug Load
SELECT  friendly_id_slugs.* FROM friendly_id_slugs WHERE friendly_id_slugs.sluggable_id = 9999 AND friendly_id_slugs.sluggable_type = 'Thing' ORDER BY friendly_id_slugs.id DESC LIMIT 1;
-- FriendlyId::Slug Destroy
DELETE FROM friendly_id_slugs WHERE friendly_id_slugs.sluggable_id = 9999 AND friendly_id_slugs.sluggable_type = 'Thing' AND friendly_id_slugs.slug = 'poodle' AND friendly_id_slugs.scope = 'account_id:1'
-- Thing Load
SELECT  things.* FROM things WHERE things.id = 9999 LIMIT 1
-- FriendlyId::Slug Create
INSERT INTO friendly_id_slugs (slug, sluggable_id, sluggable_type, scope, …
```
> Remove MySQL deadlock caused by delete_all in history.

- .github/workflows/test.yml
When we use GitHub Actions, but we only run on the `push` event,
it only runs when someone pushes to the source repo at norman/friendly_id.
This isn't what we want, as we want to test other contributors' changes
as well.
Now Actions will run on push to master branch, and pull request.
I've also removed `max-parallel` as apparently it will already run the most
that it can according to [the docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel).
>  Run Actions on master `push` and `pull_request`

- lib/friendly_id/base.rb
- lib/friendly_id/configuration.rb
Not sure if all these are still there, but `finders` was missing
> Add :finders module to documentation comment

- .github/workflows/test.yml
- Rakefile
- test/databases.yml
The mysql jobs are failing in CI. It seems this is because there is no mysql service running. Fix by adding a mysql service to the CI config.
> Fix mysql jobs in CI build matrix

- lib/friendly_id/history.rb
This fixes the following warnings that are printed when using friendly_id with Ruby 2.7.1:
Using friendly_id @ master:
```
friendly_id-984dac788d10/lib/friendly_id/history.rb:75: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
rails-370188aea03f/activerecord/lib/active_record/associations.rb:1370: warning: The called method `has_many' is defined here
```
Using this PR, no warnings are printed.
> Fix Ruby 2.7 keyword params deprecation warning

- lib/friendly_id/slugged.rb
- test/slugged_test.rb
This PR replaces https://github.com/norman/friendly_id/pull/903. Added test to pass pipeline checks.
> Fix/Slug Validation in unset_slug_if_invalid

- .github/FUNDING.yml
To enable more time to be spent on this project, it makes sense to
link to existing GitHub sponsors.
> Add FUNDING.yml for sponsorship

- lib/friendly_id/slugged.rb
I believe this simple change solves the _issue_ #949.
> Remove unexpected :slug error on valid model, fixes #949

- Changelog.md
- lib/friendly_id/finder_methods.rb
- test/finders_test.rb
In #787 we merged a change which found slugs by `id.downcase` by
default, but this has understandably caused issues for other users of
FriendlyId who don't want to do this.
This reverts that change and introduces a new method, 
`parse_friendly_id`, which can be overridden similar to 
`normalize_friendly_id`.  
Instead of being used for slug generation, `parse_friendly_id` is used
for parsing incoming slugs.
Fixes #950
> Add `parse_friendly_id` to make slug finder downcase opt-in

- .github/workflows/test.yml
It fixes the CI after a moderate security vulnerability.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> CI: Use setup-ruby at v1

- lib/friendly_id/slugged.rb
- test/slugged_test.rb
This opens the change up for discussion and continuous integration.
Currently, this change brings in a failing test by @vfonic so that we can
get it passing.
> Generating slug when validation is skipped

- lib/friendly_id/sequentially_slugged.rb
- test/sequentially_slugged_test.rb
When custom `slug_column` is used along with `history` and
`sequentially_slugged` modules, wrong query was being formed on `Slug`
model.
Query being made - `select friendly_id_slugs."strange name" from artists`
Query which should be made - `select friendly_id_slugs.slug from artists`
This commit fixes it to use default `slug` column in such case.
> Fix "unknown column" exception

- lib/friendly_id/sequentially_slugged.rb
- lib/friendly_id/sequentially_slugged/calculator.rb
While looking at the code, I got confused about variable names inside 
`SequentiallySlugged` because there was another class nested inside the
file: `SequentialSlugCalculator`.
To avoid this confusion, I've extracted this inner class to another
file: `lib/friendly_id/sequentially_slugged/calculator.rb`.
> Extract sequential_slug_calculator to sequentially_slugged/calculator

- lib/friendly_id/simple_i18n.rb
- test/schema.rb
- test/simple_i18n_test.rb
It defines how to use slug columns for locales with region subtags.
This could result in a breaking change for people using column names like `title_pt-BR`. Here I try to be explicit about and define how to use subtags, which we currently don't.
> SimpleI18n: Handle regional locales

- .github/workflows/test.yml
- Gemfile
- gemfiles/Gemfile.rails-5.2.rb
- gemfiles/Gemfile.rails-6.0.rb
Ruby 3.0 has been out for a while and it makes sense to test FriendlyId
with it on CI.
> Add Ruby 3.0 to CI test matrix

- .github/workflows/test.yml
- gemfiles/Gemfile.rails-6.1.rb
Rails 6.1 is the latest stable release of Rails, so it makes sense to
use CI to test that we're compatible with it.
> Add Rails 6.1 to CI test matrix

- .github/workflows/test.yml
- test/databases.yml
By using resources already available on the GitHub Actions CI VM, we can
speed up CI by not pulling down large docker images and waiting for them
to start up.
This also means that, when running PostgreSQL tests, we aren't starting
MySQL and vice versa.
> Run CI databases on VM

- test/helper.rb
Mocha wants us to require `mocha/minitest` instead of `mocha/setup`.
> Fix mocha/setup deprecation

- .github/workflows/test.yml
- gemfiles/Gemfile.rails-7.0.rb
Rails 7.0 was released. This PR adds it to the CI Matrix, excluding Ruby 2.5 and 2.6 because the minimum version of Ruby required for Rails 7 is 2.7.
> Add Rails 7 to CI matrix

- .github/workflows/test.yml
- friendly_id.gemspec
Ruby 2.5 arrived to EOL. I think it is the moment to drop the support.
> Drop support for Ruby 2.5

- friendly_id.gemspec
> Modify gemspec heredoc to be compatible with earlier Ruby versions

- Changelog.md
- README.md
- lib/friendly_id/finder_methods.rb
- test/finders_test.rb
This PR adds an optional `allow_nil: true` option to the finder
From discussion in #937 the idea is to add functionality that behaves *like* Rails' `find_by` which returns `nil` when a record is not found. 
This is useful in conditions where the developer is allowing the primary key ID and the friendly slug ID but is not sure if the record will actually be found, and wants a nil instead of a raised exception.
```ruby
MyModel.friendly.find("friendly-slug")
MyModel.friendly.find("friendly-slug", allow_nil: true)
```
> Add `allow_nil: true` option to the finder

- Changelog.md
- README.md
- lib/friendly_id/finder_methods.rb
- test/finders_test.rb
Turns out, the documentation I added in #995 wasn't 100% accurate. I had
to add tests for such examples and improve the internal code to support
the option. This should now provide the fully expected behavior.
> Fix issues with `allow_nil: true`

- .yardopts
- guide.rb
- lib/friendly_id.rb
- lib/friendly_id/base.rb
- lib/friendly_id/finders.rb
- lib/friendly_id/history.rb
- lib/friendly_id/reserved.rb
- lib/friendly_id/scoped.rb
- lib/friendly_id/simple_i18n.rb
- lib/friendly_id/slugged.rb
This resolves https://github.com/norman/friendly_id/issues/1004, which fixes a bug in building the guide for yard documentation.
> Fix yard doc generation

- friendly_id.gemspec
- test/helper.rb
Currently CI is failing because we refer to `MiniTest` and the class is
`Minitest`. This is also something that Mocha is doing, which is one of
our development dependencies, but updating that fixes it.
> Upgrade Mocha in development dependencies

- lib/friendly_id/history.rb
> Fix: history not using `parse_friendly_id`

- .github/workflows/test.yml
- gemfiles/Gemfile.rails-7.1.rb
This PR does three things:
- Add Rails 7.1 to the matrix
- Drops support for Ruby 2.6 (almost 2 years EOL)
- Removes Gemfile for Rails 5.2 (well, in the code diff looks like renamed and modified because I've added the Gemfile for Rails 7.1)
> Add Rails 7.1 to CI Matrix and drop support for Ruby 2.6
